import { z } from "zod";

/**
 * Research bounded context.
 *
 * Aggregates here describe research, not the simulation. They refer to the
 * simulation only through the stable interchange contract (event references
 * and metric identifiers), so experiments stay reproducible and reports stay
 * meaningful if internal simulation components change.
 *
 * Epistemic categories are explicit and never mixed:
 *   observation    — a statement computed from recorded events or metrics
 *   metric         — a defined, computed quantity
 *   hypothesis     — a researcher-authored, operationalised conjecture
 *   interpretation — researcher-authored meaning; never generated by the system
 *
 * The repository studies virtual civilizations. It does not attempt to prove,
 * infer, or assign consciousness.
 */

const slug = z.string().regex(/^[a-z0-9][a-z0-9-]*$/);
const text = z.string().min(1);

export const EpistemicKindSchema = z.enum(["observation", "metric", "hypothesis", "interpretation", "method", "limitation", "provenance"]);
export type EpistemicKind = z.infer<typeof EpistemicKindSchema>;

/** A pointer to one recorded event in the hash-chained event store. */
export const EventRefSchema = z.object({ seq: z.number().int().min(0), type: text, hash: z.string().regex(/^[0-9a-f]{64}$/) }).strict();
export type EventRef = z.infer<typeof EventRefSchema>;

export const ResearchQuestionSchema = z.object({ id: slug, text, motivation: text }).strict();
export type ResearchQuestion = z.infer<typeof ResearchQuestionSchema>;

export const ComparatorSchema = z.enum(["==", "!=", ">", ">=", "<", "<="]);
export type Comparator = z.infer<typeof ComparatorSchema>;

/** A hypothesis must be operationalised as a metric test to be evaluated. */
export const HypothesisSchema = z
  .object({
    id: slug,
    questionId: slug,
    statement: text,
    operationalisation: z.object({ metric: z.string().regex(/^[a-z_]+(\.[a-z_]+)+$/), comparator: ComparatorSchema, threshold: z.number() }).strict(),
  })
  .strict();
export type Hypothesis = z.infer<typeof HypothesisSchema>;

export const MetricDefinitionSchema = z.object({ id: z.string(), name: text, unit: text, definition: text }).strict();
export type MetricDefinition = z.infer<typeof MetricDefinitionSchema>;

export const MetricValueSchema = z.object({ metric: z.string(), value: z.number() }).strict();
export type MetricValue = z.infer<typeof MetricValueSchema>;

/**
 * What a run is for. A demonstration's protagonists act as the scenario
 * scripts them, so its findings show that the platform and the declared law
 * tables produce the declared outcome; they are not observations of what
 * citizens would do. An experiment's outcome is not scripted.
 */
export const ExperimentCategorySchema = z.enum(["demonstration", "experiment"]);
export type ExperimentCategory = z.infer<typeof ExperimentCategorySchema>;
export const CATEGORY_MEANING: Record<ExperimentCategory, string> = {
  demonstration: "the protagonists' actions are authored by the scenario, so a finding consistent with its hypothesis shows that the platform and the declared law tables produce the declared outcome. It is not evidence about what citizens would do.",
  experiment: "the outcome is not scripted; findings are observations of this run under the declared rules, seed and parameters.",
};

export const ExperimentSchema = z
  .object({
    id: slug,
    title: text,
    category: ExperimentCategorySchema,
    civilizationId: slug,
    questionId: slug,
    hypothesisIds: z.array(slug),
    scenario: slug,
    seed: text,
    simulationVersion: text,
    configurationHash: z.string().regex(/^[0-9a-f]{64}$/),
    startedAt: z.string().datetime(),
    endedAt: z.string().datetime(),
    eventStore: z.object({ headHash: z.string().regex(/^[0-9a-f]{64}$/), eventCount: z.number().int().min(1) }).strict(),
  })
  .strict();
export type Experiment = z.infer<typeof ExperimentSchema>;

/**
 * An observation is computed, never authored. `basis` says whether it rests on
 * a metric value or on specific events; at least one trace is required.
 */
export const ObservationSchema = z
  .object({
    id: slug,
    kind: z.literal("observation"),
    basis: z.enum(["metric", "event"]),
    statement: text,
    metrics: z.array(MetricValueSchema),
    events: z.array(EventRefSchema),
  })
  .strict()
  .refine((o) => o.metrics.length + o.events.length > 0, "an observation must trace to metrics or events");
export type Observation = z.infer<typeof ObservationSchema>;

/**
 * A finding is the mechanical outcome of a hypothesis test. Its statement is
 * generated from a fixed template; it summarises, it does not conclude beyond
 * the computed comparison.
 */
export const FindingSchema = z
  .object({
    id: slug,
    hypothesisId: slug,
    metric: z.string(),
    observedValue: z.number().nullable(),
    comparator: ComparatorSchema,
    threshold: z.number(),
    outcome: z.enum(["consistent-with-hypothesis", "inconsistent-with-hypothesis", "undetermined"]),
    statement: text,
    observationIds: z.array(slug),
  })
  .strict();
export type Finding = z.infer<typeof FindingSchema>;

export const VisualizationSchema = z
  .object({
    id: slug,
    title: text,
    kind: z.enum(["graph", "network", "timeline", "timeseries", "table"]),
    dataFile: text,
    description: text,
    encoding: z.record(z.string(), z.string()),
  })
  .strict();
export type Visualization = z.infer<typeof VisualizationSchema>;

export const ChronicleStatementSchema = z
  .object({ text, events: z.array(EventRefSchema).min(1), category: text })
  .strict();
export const CivilizationChronicleSchema = z
  .object({
    civilizationId: slug,
    timeUnit: z.literal("year"),
    timeMapping: text,
    periods: z.array(z.object({ year: z.number().int().min(1), statements: z.array(ChronicleStatementSchema).min(1) }).strict()),
  })
  .strict();
export type CivilizationChronicle = z.infer<typeof CivilizationChronicleSchema>;

export const PublicationSectionSchema = z
  .object({ heading: text, kind: EpistemicKindSchema, body: z.string() })
  .strict();
export const PublicationSchema = z
  .object({
    id: slug,
    experimentId: slug,
    title: text,
    status: z.literal("draft"),
    sections: z.array(PublicationSectionSchema).min(1),
  })
  .strict();
export type Publication = z.infer<typeof PublicationSchema>;
